#ifndef _CONFIG_H_
#define _CONFIG_H_

#define MENU_NUMBER 10
#define MAX_LEN 64
#define MAX_NAME_LENGTH 20
#define MAX_PASSWORD_LENGTH 20 
#define MAX_USER_NUMBER 200
#define MAX_ID_LENGTH 20
#define MAX_SUBJECT_NUM 10
#define MAX_STUDENT_NUM 100
#define MAX_LINE_LENGTH 1024

#endif